version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - apt-get update
      - apt-get install -y nginx

  build:
    commands:
      - echo "Building and deploying Nginx application..."

artifacts:
  files:
    - '**/*'
  discard-paths: yes

cache:
  paths:
    - '/var/lib/apt/lists/*'


